name: Test Pull Request
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
